/*
Ayan Kumar Chatterjee
MCA (IGNOU), Diploma in Software Engineering (Aptech Computer Education),
Teacher of Computer Science and Software Technology
1/1A, Ananda Chatterjee Lane, Kolkata 700003.  Phone: 99034 63883 // 033 2554 6084.  Email: ayankumarchatterjee@yahoo.com
*/

/*
THE BASIC THEORY BEHIND INFIX TO PREFIX NOTATION 
CONVERSION IS AS FOLLOWS:

REVERSE THE INFIX EXPRESSION.

MAKE EVERY '(' AS ')' AND EVERY ')' AS '('

CONVERT EXPRESSION TO POSTFIX FORM. 

REVERSE THE EXPRESSION.


ALGORITHM:

STEP 1. PUSH “)” ONTO STACK, AND ADD “(“ TO END OF THE INFIX EXPRESSION

STEP 2. SCAN INFIX EXPRESSION FROM RIGHT TO LEFT AND REPEAT STEP 3 TO 6 
	FOR EACH ELEMENT OF INFIX EXPRESSION UNTIL THE STACK IS EMPTY

STEP 3. IF AN OPERAND IS ENCOUNTERED ADD IT TO PREFIX

STEP 4. IF A RIGHT PARENTHESIS IS ENCOUNTERED PUSH IT ONTO STACK

STEP 5. IF AN OPERATOR IS ENCOUNTERED THEN:
	A. REPEATEDLY POP EACH OPERATOR FROM STACK AND ADD TO POSTFIX WHICH HAS 
	SAME OR HIGHER PRECEDENCE THAN THE OPERATOR IN INFIX EXPRESSION.
	B. ADD OPERATOR TO STACK

STEP 6. IF LEFT PARENTHESIS IS ENCOUNTERED THEN:
	a. REPEATEDLY POP EACH OPERATOR FROM THE STACK AND ADD TO POSTFIX 
	UNTIL A LEFT PARENTHESIS IS ENCOUNTERED
	B. REMOVE THE LEFT PARENTHESIS

STEP 7. EXIT

